### ISSUE TITLE
Review of code

### ISSUE THREAD

**Issue by pszafer** [OlliL/bosch-thermostat-mqtt#1]
Hi,
You asked about review, so I filled new issue.
- it's new code, so use typing from beginning, it's better than fixing it later
- use asyncio mqtt and class for managing mqtt
- don't reconnect on every query

Other than that it seems ok

**Comment by OlliL** [comment]
One question regarding the 3rd point - you mean reconnecting the MQTT gateway or the Bosch thermostat?

Regarding MQTT I'm not really sure I should do a keep-alive connection. It seems much easier to disconnect and reconnect again. The overhead is rather small and you don't need to worry about timed out connection. But I can check its pros and cons once more.
If you mean the Bosch thermostat - From how I see the code it should use keep-alive connections.

Whats the benefit in using asyncio mqtt for publishing?

I intended to keep the script as much the same as the original one but yeah - I'll work on type hinting! Thanks :+1:

**Comment by pszafer** [comment]
I mean mqtt.
I don't know what is the exact purpose of this client, but I think you'd want to subscribe for messages as well to act as bridge (eg set new temperature to HC) / service.
In that case it would be better to have connection open so users won't wait for connection to be established.
https://stackoverflow.com/questions/18879419/tcp-connection-keep-up-or-reconnect
You can use my code from this app as example:
https://github.com/boneIO-eu/app_bbb/blob/dev/boneio/mqtt_client.py

**Comment by OlliL** [comment]
Ah OK I see. Well, its only meant for emitting data and not subscribing to any topics.

It could be transformed into a real mqtt bridge, yes - but I'll leave that to someone else.
I'm only interested in geting the thermostat data emitted via mqtt. I'll work on your 3 points and see what I can achive.

Thanks for sharing your thoughts with me.

**Comment by OlliL** [comment]
OK well, I'm giving up on this. The existing bosch_cli code is missing plenty of type hints already and it seem not easy to get it 100% typed. While there is a type stubs libraries for paho mqtt I just don't see the point to invest more time into this.

Thanks for the review but I'll leave it as it is for now.
